//! Core data types for ech0.
//!
//! Contains the graph schema (`Node`, `Edge`), memory tier classification,
//! and all result types returned by `Store` operations.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "contradiction-detection")]
use crate::conflict::ConflictReport;

#[cfg(all(feature = "dynamic-linking", feature = "tokio"))]
use crate::linking::LinkingResult;

// ---------------------------------------------------------------------------
// Graph schema
// ---------------------------------------------------------------------------

/// A node in the knowledge graph. Represents a single memory — a fact, event,
/// or concept extracted from ingested text.
///
/// `metadata` is a caller-controlled open bag. ech0 never reads or validates
/// metadata contents — it stores and returns it as-is.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Node {
    /// Unique identifier for this node. Generated by ech0 on ingest.
    pub id: Uuid,

    /// Caller-defined type label (e.g. "person", "event", "fact").
    pub kind: String,

    /// Open metadata bag — caller puts whatever they need, ech0 stores it opaquely.
    pub metadata: serde_json::Value,

    /// Importance score. Increases on retrieval and linking, decreases with decay.
    /// Range is not clamped — caller and config determine semantics.
    pub importance: f32,

    /// When this node was first ingested.
    pub created_at: DateTime<Utc>,

    /// The ingest operation that created this node. Groups nodes from the same ingest call.
    pub ingest_id: Uuid,

    /// Original source text that produced this node. Only populated when the
    /// `provenance` feature is enabled; `None` otherwise.
    pub source_text: Option<String>,
}

/// A directed edge in the knowledge graph. Connects two `Node`s with a named relation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Edge {
    /// Source node ID.
    pub source: Uuid,

    /// Target node ID.
    pub target: Uuid,

    /// Relationship label (e.g. "knows", "occurred_at", "contradicts").
    pub relation: String,

    /// Open metadata bag — same semantics as `Node::metadata`.
    pub metadata: serde_json::Value,

    /// Importance score for this edge. Same decay/boost semantics as nodes.
    pub importance: f32,

    /// When this edge was first ingested.
    pub created_at: DateTime<Utc>,

    /// The ingest operation that created this edge.
    pub ingest_id: Uuid,
}

// ---------------------------------------------------------------------------
// Memory tiers
// ---------------------------------------------------------------------------

/// Classification of memory lifespan and retrieval behavior.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MemoryTier {
    /// Current session working context. Short lifespan, always injected on retrieval.
    ShortTerm,

    /// Time-stamped events that happened. Long lifespan, decays slowly.
    /// Retrieved by recency + relevance.
    Episodic,

    /// General facts, relationships, attributes. Long lifespan, decays by importance.
    /// Retrieved by semantic similarity + graph traversal.
    Semantic,
}

// ---------------------------------------------------------------------------
// Ingest result
// ---------------------------------------------------------------------------

/// Result of an `ingest_text()` or `ingest_nodes()` call.
pub struct IngestResult {
    /// Unique identifier for this ingest operation. All nodes and edges created
    /// by this ingest share this ID.
    pub ingest_id: Uuid,

    /// Number of nodes written to the graph layer.
    pub nodes_written: usize,

    /// Number of edges written to the graph layer.
    pub edges_written: usize,

    /// Contradictions detected during ingest. Empty when the
    /// `contradiction-detection` feature is disabled.
    #[cfg(feature = "contradiction-detection")]
    pub conflicts: Vec<ConflictReport>,

    /// A-MEM dynamic linking background task handle. The caller can `await` it
    /// to wait for linking to complete, or drop it to let it run in the background.
    ///
    /// `None` when the `dynamic-linking` feature is disabled or when there are
    /// no nodes to link (e.g. `ingest_nodes` with an empty set).
    #[cfg(all(feature = "dynamic-linking", feature = "tokio"))]
    pub linking_task: Option<tokio::task::JoinHandle<LinkingResult>>,
}

// Implement Debug manually because JoinHandle does not implement Debug in a
// way that is useful, and feature-gated fields make derive cumbersome.
impl std::fmt::Debug for IngestResult {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut debug_struct = formatter.debug_struct("IngestResult");
        debug_struct
            .field("ingest_id", &self.ingest_id)
            .field("nodes_written", &self.nodes_written)
            .field("edges_written", &self.edges_written);

        #[cfg(feature = "contradiction-detection")]
        debug_struct.field("conflicts", &self.conflicts);

        #[cfg(all(feature = "dynamic-linking", feature = "tokio"))]
        debug_struct.field("linking_task", &self.linking_task.as_ref().map(|_| "..."));

        debug_struct.finish()
    }
}

// ---------------------------------------------------------------------------
// Search types
// ---------------------------------------------------------------------------

/// Options controlling hybrid search behavior.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchOptions {
    /// Hard cap on the number of results returned. This is a maximum, not a target.
    pub limit: usize,

    /// Weight given to vector similarity results. Range: 0.0–1.0.
    /// Combined with `graph_weight` to rank merged results.
    pub vector_weight: f32,

    /// Weight given to graph traversal results. Range: 0.0–1.0.
    pub graph_weight: f32,

    /// Minimum importance score. Nodes below this threshold are filtered out
    /// before returning results.
    pub min_importance: f32,

    /// Which memory tiers to search. Empty means search all tiers.
    pub tiers: Vec<MemoryTier>,
}

impl Default for SearchOptions {
    fn default() -> Self {
        Self {
            limit: 10,
            vector_weight: 0.5,
            graph_weight: 0.5,
            min_importance: 0.0,
            tiers: Vec::new(),
        }
    }
}

/// Result of a hybrid search operation.
#[derive(Debug, Clone)]
pub struct SearchResult {
    /// Nodes matching the query, scored and sorted by combined relevance.
    pub nodes: Vec<ScoredNode>,

    /// Edges connecting the returned nodes (context for the caller).
    pub edges: Vec<ScoredEdge>,

    /// Explanation of how each result was found — vector path, graph path, or both.
    pub retrieval_path: Vec<RetrievalStep>,
}

/// A node with its computed relevance score.
#[derive(Debug, Clone)]
pub struct ScoredNode {
    /// The node itself.
    pub node: Node,

    /// Combined relevance score from vector similarity and graph traversal.
    pub score: f32,

    /// How this node was found.
    pub source: RetrievalSource,
}

/// An edge with its computed relevance score.
#[derive(Debug, Clone)]
pub struct ScoredEdge {
    /// The edge itself.
    pub edge: Edge,

    /// Relevance score derived from connected node scores.
    pub score: f32,
}

/// Describes how a particular result was found during hybrid search.
#[derive(Debug, Clone)]
pub struct RetrievalStep {
    /// The node this step describes.
    pub node_id: Uuid,

    /// How this node was discovered.
    pub source: RetrievalSource,

    /// Score contributed by vector similarity (0.0 if not found via vector).
    pub vector_score: f32,

    /// Score contributed by graph traversal (0.0 if not found via graph).
    pub graph_score: f32,

    /// Final combined score after weighting.
    pub combined_score: f32,
}

/// Origin of a search result.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RetrievalSource {
    /// Found via vector ANN similarity search.
    Vector,

    /// Found via graph relationship traversal.
    Graph,

    /// Found by both vector and graph paths — scores were merged.
    Both,
}

// ---------------------------------------------------------------------------
// Traversal types
// ---------------------------------------------------------------------------

/// Options controlling graph traversal behavior.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraversalOptions {
    /// Maximum depth of traversal hops from the starting node.
    pub max_depth: usize,

    /// Maximum number of nodes to return.
    pub limit: usize,

    /// Minimum importance score for traversed nodes. Nodes below this are skipped.
    pub min_importance: f32,

    /// If set, only follow edges with these relation labels.
    pub relation_filter: Option<Vec<String>>,
}

impl Default for TraversalOptions {
    fn default() -> Self {
        Self {
            max_depth: 3,
            limit: 50,
            min_importance: 0.0,
            relation_filter: None,
        }
    }
}

/// Result of a graph traversal from a starting node.
#[derive(Debug, Clone)]
pub struct TraversalResult {
    /// Nodes discovered during traversal, ordered by discovery (BFS order).
    pub nodes: Vec<Node>,

    /// Edges traversed to discover those nodes.
    pub edges: Vec<Edge>,

    /// Maximum depth actually reached during traversal.
    pub depth_reached: usize,
}

// ---------------------------------------------------------------------------
// Decay / prune report types
// ---------------------------------------------------------------------------

/// Report from a `decay()` call describing what changed.
#[derive(Debug, Clone)]
pub struct DecayReport {
    /// Number of nodes whose importance score was decreased.
    pub nodes_decayed: usize,

    /// Number of edges whose importance score was decreased.
    pub edges_decayed: usize,

    /// Number of nodes that fell below the prune threshold (not yet pruned —
    /// call `prune()` to remove them).
    pub nodes_below_threshold: usize,
}

/// Report from a `prune()` call describing what was removed.
#[derive(Debug, Clone)]
pub struct PruneReport {
    /// Number of nodes removed because their importance was below the threshold.
    pub nodes_pruned: usize,

    /// Number of edges removed because one or both connected nodes were pruned.
    pub edges_pruned: usize,

    /// Number of vector embeddings removed from the usearch index.
    pub vectors_pruned: usize,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn node_round_trips_through_json() {
        let node = Node {
            id: Uuid::new_v4(),
            kind: "person".to_string(),
            metadata: serde_json::json!({"name": "Alice", "age": 30}),
            importance: 0.8,
            created_at: Utc::now(),
            ingest_id: Uuid::new_v4(),
            source_text: Some("Alice is 30 years old.".to_string()),
        };

        let serialized = serde_json::to_string(&node).expect("node should serialize to JSON");
        let deserialized: Node =
            serde_json::from_str(&serialized).expect("JSON should deserialize back to Node");

        assert_eq!(deserialized.id, node.id);
        assert_eq!(deserialized.kind, node.kind);
        assert_eq!(deserialized.metadata, node.metadata);
        assert!((deserialized.importance - node.importance).abs() < f32::EPSILON);
        assert_eq!(deserialized.ingest_id, node.ingest_id);
        assert_eq!(deserialized.source_text, node.source_text);
    }

    #[test]
    fn edge_round_trips_through_json() {
        let edge = Edge {
            source: Uuid::new_v4(),
            target: Uuid::new_v4(),
            relation: "knows".to_string(),
            metadata: serde_json::json!({"since": "2024"}),
            importance: 0.6,
            created_at: Utc::now(),
            ingest_id: Uuid::new_v4(),
        };

        let serialized = serde_json::to_string(&edge).expect("edge should serialize to JSON");
        let deserialized: Edge =
            serde_json::from_str(&serialized).expect("JSON should deserialize back to Edge");

        assert_eq!(deserialized.source, edge.source);
        assert_eq!(deserialized.target, edge.target);
        assert_eq!(deserialized.relation, edge.relation);
    }

    #[test]
    fn node_round_trips_through_msgpack() {
        let node = Node {
            id: Uuid::new_v4(),
            kind: "fact".to_string(),
            metadata: serde_json::json!({"statement": "the sky is blue"}),
            importance: 1.0,
            created_at: Utc::now(),
            ingest_id: Uuid::new_v4(),
            source_text: None,
        };

        let bytes = rmp_serde::to_vec(&node).expect("node should serialize to msgpack");
        let deserialized: Node =
            rmp_serde::from_slice(&bytes).expect("msgpack should deserialize back to Node");

        assert_eq!(deserialized.id, node.id);
        assert_eq!(deserialized.kind, node.kind);
    }

    #[test]
    fn edge_round_trips_through_msgpack() {
        let edge = Edge {
            source: Uuid::new_v4(),
            target: Uuid::new_v4(),
            relation: "occurred_at".to_string(),
            metadata: serde_json::json!({}),
            importance: 0.5,
            created_at: Utc::now(),
            ingest_id: Uuid::new_v4(),
        };

        let bytes = rmp_serde::to_vec(&edge).expect("edge should serialize to msgpack");
        let deserialized: Edge =
            rmp_serde::from_slice(&bytes).expect("msgpack should deserialize back to Edge");

        assert_eq!(deserialized.source, edge.source);
        assert_eq!(deserialized.target, edge.target);
        assert_eq!(deserialized.relation, edge.relation);
    }

    #[test]
    fn memory_tier_equality() {
        assert_eq!(MemoryTier::ShortTerm, MemoryTier::ShortTerm);
        assert_ne!(MemoryTier::ShortTerm, MemoryTier::Episodic);
        assert_ne!(MemoryTier::Episodic, MemoryTier::Semantic);
    }

    #[test]
    fn search_options_default_is_balanced() {
        let options = SearchOptions::default();
        assert_eq!(options.limit, 10);
        assert!((options.vector_weight - 0.5).abs() < f32::EPSILON);
        assert!((options.graph_weight - 0.5).abs() < f32::EPSILON);
        assert!((options.min_importance - 0.0).abs() < f32::EPSILON);
        assert!(options.tiers.is_empty(), "default should search all tiers");
    }

    #[test]
    fn traversal_options_default() {
        let options = TraversalOptions::default();
        assert_eq!(options.max_depth, 3);
        assert_eq!(options.limit, 50);
        assert!((options.min_importance - 0.0).abs() < f32::EPSILON);
        assert!(options.relation_filter.is_none());
    }

    #[test]
    fn retrieval_source_variants() {
        assert_ne!(RetrievalSource::Vector, RetrievalSource::Graph);
        assert_ne!(RetrievalSource::Graph, RetrievalSource::Both);
        assert_eq!(RetrievalSource::Vector, RetrievalSource::Vector);
    }

    #[test]
    fn ingest_result_debug_does_not_panic() {
        let result = IngestResult {
            ingest_id: Uuid::new_v4(),
            nodes_written: 3,
            edges_written: 2,
            #[cfg(feature = "contradiction-detection")]
            conflicts: Vec::new(),
            #[cfg(all(feature = "dynamic-linking", feature = "tokio"))]
            linking_task: None,
        };
        // Verify Debug impl works without panicking
        let debug_output = format!("{result:?}");
        assert!(debug_output.contains("IngestResult"));
        assert!(debug_output.contains("nodes_written"));
    }
}
